server.port=8080
spring.application.name=menu-planner

# OptaPlanner configuration
optaplanner.solver.termination.spent-limit=5s

# Google Calendar configuration
google.calendar.api-key=
google.calendar.calendar-id=primary
google.calendar.enabled=false